# Generated by Django 2.1.5 on 2019-01-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190108_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='year_of_purchase',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
