# Generated by Django 2.1.5 on 2019-01-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190108_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='vehicle_type',
        ),
        migrations.AddField(
            model_name='post',
            name='distance_travelled',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='mileage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
